"""remove date column

Revision ID: 1bd7606116dd
Revises: 622db862f207
Create Date: 2020-12-31 13:55:52.031353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1bd7606116dd"
down_revision = "622db862f207"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("infos", "date")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "infos", sa.Column("date", sa.DATE(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
