"""change date type

Revision ID: 622db862f207
Revises: 9b35c55cefef
Create Date: 2020-12-31 13:53:40.751437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "622db862f207"
down_revision = "9b35c55cefef"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
