"""added date column

Revision ID: 8bed42f148a6
Revises: 1bd7606116dd
Create Date: 2020-12-31 13:56:32.521464

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8bed42f148a6"
down_revision = "1bd7606116dd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("infos", sa.Column("date", sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("infos", "date")
    # ### end Alembic commands ###
