"""Added date column

Revision ID: 9b35c55cefef
Revises:
Create Date: 2020-12-31 13:29:31.549229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9b35c55cefef"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("infos", sa.Column("date", sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("infos", "date")
    # ### end Alembic commands ###
